# Generated by Django 2.0.9 on 2018-11-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo',
            field=models.CharField(default='one off', max_length=200),
            preserve_default=False,
        ),
    ]
