# Generated by Django 2.0.9 on 2018-11-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.URLField(),
        ),
    ]
