# Generated by Django 2.0.9 on 2018-11-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='project_images/default_project.png', upload_to='project_images'),
        ),
    ]
