# Generated by Django 2.0.9 on 2018-11-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_technology'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technology',
            new_name='Technologies',
        ),
    ]
