# Generated by Django 2.0.9 on 2018-11-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='slug',
            field=models.SlugField(default='one-off', max_length=72),
            preserve_default=False,
        ),
    ]
