# Generated by Django 2.0.9 on 2018-11-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_technologies_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='slug',
            field=models.SlugField(),
        ),
    ]
