# Generated by Django 2.0.9 on 2018-11-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20181124_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=168),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
