# Generated by Django 2.0.9 on 2018-11-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20181125_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technologies',
            new_name='Keywords',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='technologies',
            new_name='keywords',
        ),
    ]
