# Generated by Django 2.0.9 on 2018-12-06 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20181125_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name_plural': 'keywords'},
        ),
    ]
