# Generated by Django 2.0.9 on 2018-12-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20181205_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
