# Generated by Django 2.0.9 on 2018-12-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_display_on_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='display_on_homepage',
            new_name='displayed_on_home_page',
        ),
    ]
