# Generated by Django 2.0.9 on 2018-12-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='text',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
