# Generated by Django 2.0.9 on 2018-12-07 23:23

from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='meta_images')),
                ('meta_description', models.CharField(max_length=160)),
                ('display', models.BooleanField(default=False)),
            ],
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.RenameField(
            model_name='about',
            old_name='displayed_on_about_page',
            new_name='display',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='meta_description',
        ),
    ]
