# Generated by Django 2.0.9 on 2018-12-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20181207_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharingmeta',
            old_name='meta_description',
            new_name='description',
        ),
    ]
