# Generated by Django 2.0.9 on 2018-12-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20181207_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingmeta',
            name='url',
            field=models.CharField(default='default', max_length=12),
            preserve_default=False,
        ),
    ]
