# Generated by Django 2.0.9 on 2018-12-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_remove_sharingmeta_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingmeta',
            name='url',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
