# Generated by Django 2.0.9 on 2018-12-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20181207_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='text',
            field=models.TextField(default='notblank'),
            preserve_default=False,
        ),
    ]
