# Generated by Django 2.0.9 on 2018-12-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_project_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='description',
            field=models.CharField(default='default', max_length=168),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keywords',
            name='image',
            field=models.ImageField(default=None, upload_to='keyword_meta_images'),
        ),
        migrations.AddField(
            model_name='keywords',
            name='title',
            field=models.CharField(default='default', max_length=60),
            preserve_default=False,
        ),
    ]
