# Generated by Django 2.0.9 on 2018-12-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20181210_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='image',
            field=models.ImageField(null=True, upload_to='keyword_meta_images'),
        ),
    ]
