# Generated by Django 2.0.9 on 2018-12-10 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20181210_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='description',
        ),
        migrations.RemoveField(
            model_name='keywords',
            name='image',
        ),
        migrations.RemoveField(
            model_name='keywords',
            name='title',
        ),
    ]
