# Generated by Django 2.0.9 on 2018-12-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20181210_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('url', models.URLField()),
            ],
        ),
    ]
