# Generated by Django 2.0.9 on 2018-12-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingmeta',
            name='contact_line',
            field=models.TextField(default='defaut'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharingmeta',
            name='linkedin',
            field=models.URLField(default='default', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharingmeta',
            name='twitter',
            field=models.URLField(default='default', max_length=160),
            preserve_default=False,
        ),
    ]
