# Generated by Django 2.0.9 on 2018-12-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20181212_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
