# Generated by Django 2.0.9 on 2018-12-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_delete_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingmeta',
            name='github',
            field=models.URLField(default='https://github.com/jdavv', max_length=160),
            preserve_default=False,
        ),
    ]
